### ISSUE TITLE
BTC Dominance (BTC.D) and total crypto market cap (TOTAL)

### ISSUE THREAD

**Issue by returnsomeday2** [brian-the-dev/python-tradingview-ta#85] opened 2022-02-21 23:50 UTC
Hi,

wondering how can I access the above symbols (BTC.D, TOTAL). They are not associated with any exchange/screener?

**Comment by brian-the-dev** [comment] 2022-02-21 23:52
Duplicate of #84.

**Closed by brian-the-dev** 2022-02-21 23:52 UTC
Labels: enhancement
