### ISSUE TITLE
TypeError: 'TradingView' object is not iterable

### ISSUE THREAD

**Issue by Upasanadhameliya** [brian-the-dev/python-tradingview-ta#69] opened 2021-09-15 08:59 UTC
- When trying to call the `data()` function of the `TradingView` class in `main.py`, Error is thrown.
It might be due to the fact that `self` parameter was mistakenly not defined in this method.
https://github.com/brian-the-dev/python-tradingview-ta/blob/b227188ab1a53eb0a96623ee631bb11c25213644/tradingview_ta/main.py#L44

- In order to get this error I ran the following code:
```
from tradingview_ta import TradingView
tv = TradingView()
tv.data("NASDAQ:AAPL","1m")
```
- Error Traceback:
```
C:\Users\Upasana Dhameliya\.conda\envs\tradingview38\lib\site-packages\tradingview_ta\main.py:83: UserWarning: Interval is empty or not valid, defaulting to 1 day.
  warnings.warn("Interval is empty or not valid, defaulting to 1 day.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Upasana Dhameliya\.conda\envs\tradingview38\lib\site-packages\tradingview_ta\main.py", line 87, in data
    data_json = {"symbols":{"tickers":[symbol.upper() for symbol in symbols],"query":{"types":[]}},"columns":[x + data_interval for x in indicators]}
TypeError: 'TradingView' object is not iterable
```

**Version**
 - OS: Windows 10 - Anaconda Prompt
 - Python: 3.8.11
 - TradingView-TA: 3.2.9

**Comment by brian-the-dev** [comment] 2021-09-15 09:16
Hi @Upasanadhameliya,

The `data()` function (and the `TradingView` class) is not intended to be used directly. It's only used in another function inside tradingview-ta's code (to create JSON data that is then sent to the server). Instead, you should use the `get_analysis()` function after instantiating `TA_Handler`

Please see the [example](https://github.com/brian-the-dev/python-tradingview-ta#example) and read the [documentation](https://python-tradingview-ta.readthedocs.io/). I'm closing this issue as your error was caused by unintended use. If you have any questions, please reply below.

**Closed by brian-the-dev** 2021-09-15 09:16 UTC
Labels: bug
