### ISSUE TITLE
value is None in Recommend

### ISSUE THREAD

**Issue by oozcan98** [brian-the-dev/python-tradingview-ta#55] opened 2021-07-24 08:42 UTC
Hi,
Thanks for your code.
I try to call get_multiple_analysis with a list of symbols  

if value is None in Recommend at technicals.py function crushes , i expect the list which has available result

you can add at begin of Recommend.py
    
if value is None:
     return Recommendation.error

Thanks for advance

**Comment by brian-the-dev** [comment] 2021-07-24 09:35
Hi @oozcan98,

Can you reply with a snippet of your code? I'd like to see the error.

**Comment by oozcan98** [comment] 2021-07-24 10:26
Hi ,

you can try it

from tradingview_ta import TA_Handler, Interval, get_multiple_analysis
from datetime import datetime
from binance.client import Client

client = Client('', '')

now = datetime.now()
now_time = now.strftime("%d-%m-%y %H:%M:%S")
listb = client.get_all_tickers()
lista = ['BINANCE:' + x['symbol'] for x in listb if 'USDT' in x['symbol']]
analiz = get_multiple_analysis(screener='crypto',
                               symbols=lista,
                               interval=Interval.INTERVAL_1_DAY)

**Comment by brian-the-dev** [comment] 2021-07-24 10:36
Seems like this issue was caused by https://www.tradingview.com/symbols/DEXEUSDT/technicals/ which has no technical analysis. I'll fix this in a jiffy.

**Comment by brian-the-dev** [comment] 2021-07-24 11:25
The fix was published in 3.2.7. Please update tradingview_ta with `pip install -U tradingview-ta`. 

Now, if there is no analysis, it will be replaced with a `None`. For example, `BINANCE:DEXEUSDT` does not have an analysis, but `BINANCE:BTCUSDT` has:

```python
from tradingview_ta import Interval, get_multiple_analysis

analysis = get_multiple_analysis(screener="crypto", interval=Interval.INTERVAL_1_DAY, symbols=["binance:dexeusdt", "binance:btctusdt"])

print(analysis)

# Output: {'BINANCE:DEXEUSDT': None, 'BINANCE:BTCUSDT': <tradingview_ta.main.Analysis object at 0x7f3561cdeb20>}
```

Please reply if you still have any issues. Otherwise, you may close it.

**Closed** 2021-07-24 11:52 UTC
Labels: bug

**Comment by MYHMYH** [comment] 2021-09-09 04:18
Thanks 😊🙏😊🙏

**Comment by mustafaerdogan90** [comment] 2022-08-16 01:25
> Hi ,
> 
> you can try it
> 
> from tradingview_ta import TA_Handler, Interval, get_multiple_analysis from datetime import datetime from binance.client import Client
> 
> client = Client('', '')
> 
> now = datetime.now() now_time = now.strftime("%d-%m-%y %H:%M:%S") listb = client.get_all_tickers() lista = ['BINANCE:' + x['symbol'] for x in listb if 'USDT' in x['symbol']] analiz = get_multiple_analysis(screener='crypto', symbols=lista, interval=Interval.INTERVAL_1_DAY)

> Hi ,
> 
> you can try it
> 
> from tradingview_ta import TA_Handler, Interval, get_multiple_analysis from datetime import datetime from binance.client import Client
> 
> client = Client('', '')
> 
> now = datetime.now() now_time = now.strftime("%d-%m-%y %H:%M:%S") listb = client.get_all_tickers() lista = ['BINANCE:' + x['symbol'] for x in listb if 'USDT' in x['symbol']] analiz = get_multiple_analysis(screener='crypto', symbols=lista, interval=Interval.INTERVAL_1_DAY)

Ne yaptıysam get_multiple_analysis'i çalıştıramadım.
Tradingview berbat bu konuda.

**Comment by brian-the-dev** [comment] 2022-08-16 01:37
Hi @mustafaerdogan90,

This issue was resolved over a year ago. If you are having problems, please [open a new issue](https://github.com/brian-the-dev/python-tradingview-ta/issues/new?assignees=&labels=bug&template=bug_report.md&title=). Also, check if you're running the latest version on python-tradingview-ta.

**Comment by mustafaerdogan90** [comment] 2022-08-16 02:32
> 

I am using Visual Studio Enterprise 2022, Python 3.9 and the current version of Tradingview_TA. The problem, unfortunately, is also the API.
