### ISSUE TITLE
TimeoutError: [WinError 10060] 

### ISSUE THREAD

**Issue by MelanRain** [brian-the-dev/python-tradingview-ta#83] opened 2022-02-18 12:35 UTC
Hello! I use this program in the background with a record in the database. In the middle of the night, the program shuts down with the following error. There are no problems with the Internet connection, I checked it on several Internet sources. I don't use a proxy. What could be the problem?
ERROR:
Traceback (most recent call last):
  File "C:\Users\Yakov\PycharmProjects\TrVw\venv\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Yakov\PycharmProjects\TrVw\venv\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\Yakov\PycharmProjects\TrVw\venv\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] An attempt to establish a connection was unsuccessful. from another required time, the required response was not received, or an already established connection was terminated due to an incorrect response of an already connected computer

**Comment by brian-the-dev** [comment] 2022-02-18 13:03
Hi @MelanRain,

The error was not caused by tradingview-ta, but your program wasn't able to communicate with the database. Even if your internet connection is fine, the database might be down during that moment. I'd suggest that you use [try-except](https://stackoverflow.com/a/17533149) to retry connecting to the database. 

I'm going to close this issue as this is unrelated to tradingview-ta. Don't hesitate to reply if you have questions related to tradingview-ta. Have a nice day.

**Closed by brian-the-dev** 2022-02-18 13:03 UTC
Labels: bug, invalid

**Comment by MelanRain** [comment] 2022-02-18 13:19
Why is urllib3\connection.py listed in this error
